import { JisonParser, JisonParserApi, StateType, SymbolsType, TerminalsType, ProductionsType } from '@ts-jison/parser';
/**
 * parser generated by  @ts-jison/parser-generator 0.4.1-alpha.2
 * @returns Parser implementing JisonParserApi and a Lexer implementing JisonLexerApi.
 */

interface Loc {
  first_line:   number
  last_line:    number
  first_column: number
  last_column:  number
}

export class KnowsParserState {
  readonly people   = new Map<string, number>()
  readonly knowses  = new Map<string, [string, number][]>()
  readonly warnings: string[] = []

  static cap (s: string): string {
    return s.charAt(0).toUpperCase() + s.slice(1)
  }

  addPerson (name: string, loc: Loc): void {
    if (!this.people.has(name)) this.people.set(name, loc.first_line)
  }

  addKnows (subj: string, obj: string, loc: Loc): void {
    const list = this.knowses.get(subj)
    if (list) {
      list.push([obj, loc.first_line])
    } else {
      this.knowses.set(subj, [[obj, loc.first_line]])
    }
  }

  addWarning (msg: string): void {
    this.warnings.push(msg)
  }

  result (): { people: Map<string, number>; knowses: Map<string, [string, number][]>; warnings: string[] } {
    return { people: this.people, knowses: this.knowses, warnings: this.warnings }
  }
}

export class KnowsParser extends JisonParser implements JisonParserApi {
    $?: any;
    symbols_: SymbolsType = {"error":2,"document":3,"stmts":4,"EOF":5,"stmt":6,"NAME":7,"IT_KNOWS":8,"dot_Opt":9,".":10,"$accept":0,"$end":1};
    terminals_: TerminalsType = {2:"error",5:"EOF",7:"NAME",8:"IT_KNOWS",10:"."};
    productions_: ProductionsType = [0,[3,2],[4,0],[4,2],[6,4],[9,0],[9,1]];
    table: Array<StateType>;
    defaultActions: {[key:number]: any} = {3:[2,1]};

    constructor (yy: any = {}, lexer = new KnowsLexer(yy)) {
      super(yy, lexer);

      // shorten static method to just `o` for terse STATE_TABLE
      const $V0=[5,7];
      const o = JisonParser.expandParseTable;
      this.table = [o($V0,[2,2],{3:1,4:2}),{1:[3]},{5:[1,3],6:4,7:[1,5]},{1:[2,1]},o($V0,[2,3]),{8:[1,6]},{7:[1,7]},o($V0,[2,5],{9:8,10:[1,9]}),o($V0,[2,4]),o($V0,[2,6])];
    }

    performAction (yytext:string, yyleng:number, yylineno:number, yy:any, yystate:number /* action[1] */, $$:any /* vstack */, _$:any /* lstack */): any {
/* this == yyval */
          var $0 = $$.length - 1;
        switch (yystate) {
case 1: // document → stmts EOF
  return (yy as KnowsParserState).result();
break;
case 2: // stmts → ε
break;
case 3: // stmts → stmts stmt
break;
case 4: // stmt → NAME IT_KNOWS NAME dot_Opt
{
    const state = yy as KnowsParserState
    const subj = KnowsParserState.cap($$[$0-3])
    const obj  = KnowsParserState.cap($$[$0-1])
    state.addPerson(subj, _$[$0-3])
    state.addPerson(obj,  _$[$0-1])
    state.addKnows(subj, obj, _$[$0-3])
}
break;
        }
    }
}


/* generated by @ts-jison/lexer-generator 0.4.1-alpha.2 */
import { JisonLexer, JisonLexerApi } from '@ts-jison/lexer';

export class KnowsLexer extends JisonLexer implements JisonLexerApi {
    options: any = {"moduleName":"Knows"};
    constructor (yy = {}) {
        super(yy);
    }

    rules: RegExp[] = [
        /^(?:\s+|#[^\n]*)/,
        /^(?:[Kk][Nn][Oo][Ww][Ss])/,
        /^(?:[A-Za-z][A-Za-z0-9_-]*)/,
        /^(?:\.)/,
        /^(?:$)/,
        /^(?:.)/
    ];
    conditions: any = {"INITIAL":{"rules":[0,1,2,3,4,5],"inclusive":true}}
    performAction (yy:any,yy_:any,$avoiding_name_collisions:any,YY_START:any): any {
          var YYSTATE=YY_START;
        switch($avoiding_name_collisions) {
    case 0:/* skip */
      break;
    case 1:return 8;
    case 2:return 7;
    case 3:return 10;
    case 4:return 5;
    case 5: return 'invalid:'+yy_.yytext;
        }
    }
}


